In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)
pd.set_option('display.max_rows', 100)

def sparsity_report(df, name):
    n = len(df)
    nulls = df.isna().sum()
    pct = (nulls / n * 100).round(2)
    rep = pd.DataFrame({'null_count': nulls, 'null_pct': pct, 'dtype': df.dtypes}).sort_values('null_pct', ascending=False)
    print(f"--- {name}: sparsity ---")
    print(rep)
    return rep

In [2]:
osha = pd.read_csv('osha-hazards-outcome/January2015toNovember2025.csv', low_memory=False)
print('OSHA shape:', osha.shape)
osha.dtypes

OSHA shape: (105996, 28)

ID                          int64
UPA                         int64
EventDate                     str
Employer                      str
Address1                      str
Address2                      str
City                          str
State                         str
Zip                       float64
Latitude                  float64
Longitude                 float64
Primary NAICS                 str
Hospitalized              float64
Amputation                float64
Loss of Eye               float64
Inspection                    str
Final Narrative               str
Nature                      int64
NatureTitle                   str
Part of Body                int64
Part of Body Title            str
Event                       int64
EventTitle                    str
Source                      int64
SourceTitle                   str
Secondary Source          float64
Secondary Source Title        str
FederalState                int64
dtype: object

In [3]:
osha.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,105996.0,NaN,NaN,NaN,4954329221.868306,6688682183.804994,2015010010.0,2018010002.5,2021043111.5,2024087290.25,20251111775.0
UPA,105996.0,NaN,NaN,NaN,1612690.456725,421883.393628,867412.0,1254179.5,1535959.0,1987216.0,2399660.0
EventDate,105996,3985,7/10/2019,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Employer,105996,71454,U.S. Postal Service,548,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Address1,105978,89637,Unknown,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Address2,9303,8355,Suite 100,87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,105979,8221,HOUSTON,1951,NaN,NaN,NaN,NaN,NaN,NaN,NaN
State,105996,56,TEXAS,17491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zip,105972.0,NaN,NaN,NaN,47318.066829,25044.923308,716.0,30315.0,44875.0,72370.0,99926.0
Latitude,105924.0,NaN,NaN,NaN,36.589441,5.588248,-34.92,31.98,38.65,41.03,70.34
Longitude,105924.0,NaN,NaN,NaN,-87.573393,11.989609,-176.62,-95.47,-87.31,-80.56,166.64
Primary NAICS,105994,1287,622110,2467,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hospitalized,105996.0,NaN,NaN,NaN,0.816238,0.404684,0.0,1.0,1.0,1.0,6.0
Amputation,105989.0,NaN,NaN,NaN,0.263971,0.441149,0.0,0.0,0.0,1.0,2.0
Loss of Eye,105991.0,NaN,NaN,NaN,0.00033,0.018169,0.0,0.0,0.0,0.0,1.0
Inspection,35470,35311,1087712,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Final Narrative,105996,105930,An employee fell from a ladder.,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nature,105996.0,NaN,NaN,NaN,817.312955,740.279267,7.0,111.0,1110.0,1311.0,9999.0
NatureTitle,105995,349,Fractures,28480,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Part of Body,105996.0,NaN,NaN,NaN,1986.117901,2445.589981,6.0,310.0,513.0,4422.0,9999.0
Part of Body Title,105996,275,Fingertip(s),10387,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Event,105996.0,NaN,NaN,NaN,3740.499689,2446.120497,20.0,652.0,4323.0,6241.0,9999.0
EventTitle,105995,649,Caught in running equipment or machinery durin...,6687,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Source,105996.0,NaN,NaN,NaN,4753.172129,2915.023128,10.0,3122.0,4213.0,6694.0,9999.0
SourceTitle,105995,1957,"Floor, n.e.c.",5029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Secondary Source,50615.0,NaN,NaN,NaN,4146.400316,3290.907375,10.0,990.0,3440.0,6710.5,9999.0
Secondary Source Title,50614,1662,Secondary source not applicable,5771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FederalState,105996.0,NaN,NaN,NaN,0.97649,0.151518,0.0,1.0,1.0,1.0,1.0

In [4]:
sparsity_report(osha, 'OSHA hazards/outcomes')

--- OSHA hazards/outcomes: sparsity ---
                        null_count  null_pct    dtype
Address2                     96693     91.22      str
Inspection                   70526     66.54      str
Secondary Source Title       55382     52.25      str
Secondary Source             55381     52.25  float64
Latitude                        72      0.07  float64
Longitude                       72      0.07  float64
Address1                        18      0.02      str
City                            17      0.02      str
Zip                             24      0.02  float64
Amputation                       7      0.01  float64
Part of Body Title               0      0.00      str
Event                            0      0.00    int64
ID                               0      0.00    int64
EventTitle                       1      0.00      str
Source                           0      0.00    int64
NatureTitle                      1      0.00      str
SourceTitle                      1      0.00      str
Part of Body                     0      0.00    int64
Loss of Eye                      5      0.00  float64
Nature                           0      0.00    int64
Final Narrative                  0      0.00      str
UPA                              0      0.00    int64
Hospitalized                     0      0.00  float64
Primary NAICS                    2      0.00      str
State                            0      0.00      str
Employer                         0      0.00      str
EventDate                        0      0.00      str
FederalState                     0      0.00    int64

                        null_count  null_pct    dtype
Address2                     96693     91.22      str
Inspection                   70526     66.54      str
Secondary Source Title       55382     52.25      str
Secondary Source             55381     52.25  float64
Latitude                        72      0.07  float64
Longitude                       72      0.07  float64
Address1                        18      0.02      str
City                            17      0.02      str
Zip                             24      0.02  float64
Amputation                       7      0.01  float64
Part of Body Title               0      0.00      str
Event                            0      0.00    int64
ID                               0      0.00    int64
EventTitle                       1      0.00      str
Source                           0      0.00    int64
NatureTitle                      1      0.00      str
SourceTitle                      1      0.00      str
Part of Body                     0      0.00    int64
Loss of Eye                      5      0.00  float64
Nature                           0      0.00    int64
Final Narrative                  0      0.00      str
UPA                              0      0.00    int64
Hospitalized                     0      0.00  float64
Primary NAICS                    2      0.00      str
State                            0      0.00      str
Employer                         0      0.00      str
EventDate                        0      0.00      str
FederalState                     0      0.00    int64

In [5]:
storm = pd.read_csv('storm-data/StormEvents_details-ftp_v1.0_d1950_c20260323.csv', low_memory=False)
print('Storm data shape:', storm.shape)
storm.dtypes

Storm data shape: (223, 51)

BEGIN_YEARMONTH         int64
BEGIN_DAY               int64
BEGIN_TIME              int64
END_YEARMONTH           int64
END_DAY                 int64
END_TIME                int64
EPISODE_ID            float64
EVENT_ID                int64
STATE                     str
STATE_FIPS              int64
YEAR                    int64
MONTH_NAME                str
EVENT_TYPE                str
CZ_TYPE                   str
CZ_FIPS                 int64
CZ_NAME                   str
WFO                   float64
BEGIN_DATE_TIME           str
CZ_TIMEZONE               str
END_DATE_TIME             str
INJURIES_DIRECT         int64
INJURIES_INDIRECT       int64
DEATHS_DIRECT           int64
DEATHS_INDIRECT         int64
DAMAGE_PROPERTY           str
DAMAGE_CROPS            int64
SOURCE                float64
MAGNITUDE               int64
MAGNITUDE_TYPE        float64
FLOOD_CAUSE           float64
CATEGORY              float64
TOR_F_SCALE               str
TOR_LENGTH            float64
TOR_WIDTH               int64
TOR_OTHER_WFO         float64
TOR_OTHER_CZ_STATE    float64
TOR_OTHER_CZ_FIPS     float64
TOR_OTHER_CZ_NAME     float64
BEGIN_RANGE           float64
BEGIN_AZIMUTH         float64
BEGIN_LOCATION        float64
END_RANGE             float64
END_AZIMUTH           float64
END_LOCATION          float64
BEGIN_LAT             float64
BEGIN_LON             float64
END_LAT               float64
END_LON               float64
EPISODE_NARRATIVE     float64
EVENT_NARRATIVE       float64
DATA_SOURCE               str
dtype: object

In [6]:
storm.describe(include='all').T

                    count unique                 top freq             mean           std        min         25%         50%         75%         max
BEGIN_YEARMONTH     223.0    NaN                 NaN  NaN    195005.152466      2.418785   195001.0    195003.0    195005.0    195006.0    195012.0
BEGIN_DAY           223.0    NaN                 NaN  NaN        14.358744      9.196381        1.0         6.5        12.0        24.0        31.0
BEGIN_TIME          223.0    NaN                 NaN  NaN      1409.022422     619.47569        1.0      1117.5      1530.0      1830.0      2355.0
END_YEARMONTH       223.0    NaN                 NaN  NaN    195005.152466      2.418785   195001.0    195003.0    195005.0    195006.0    195012.0
END_DAY             223.0    NaN                 NaN  NaN        14.358744      9.196381        1.0         6.5        12.0        24.0        31.0
END_TIME            223.0    NaN                 NaN  NaN      1409.022422     619.47569        1.0      1117.5      1530.0      1830.0      2355.0
EPISODE_ID            0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
EVENT_ID            223.0    NaN                 NaN  NaN  10055060.721973  47040.478876  9979207.0  10027584.5  10038920.0  10096225.5  10162815.0
STATE                 223     30              KANSAS   33              NaN           NaN        NaN         NaN         NaN         NaN         NaN
STATE_FIPS          223.0    NaN                 NaN  NaN        28.336323     13.619967        1.0        20.0        24.0        40.0        56.0
YEAR                223.0    NaN                 NaN  NaN           1950.0           0.0     1950.0      1950.0      1950.0      1950.0      1950.0
MONTH_NAME            223     12                 May   64              NaN           NaN        NaN         NaN         NaN         NaN         NaN
EVENT_TYPE            223      1             Tornado  223              NaN           NaN        NaN         NaN         NaN         NaN         NaN
CZ_TYPE               223      1                   C  223              NaN           NaN        NaN         NaN         NaN         NaN         NaN
CZ_FIPS             223.0    NaN                 NaN  NaN        95.573991      77.13001        1.0        38.0        85.0       138.0       477.0
CZ_NAME               223    171              SHELBY    4              NaN           NaN        NaN         NaN         NaN         NaN         NaN
WFO                   0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
BEGIN_DATE_TIME       223    200  12-FEB-50 12:00:00    3              NaN           NaN        NaN         NaN         NaN         NaN         NaN
CZ_TIMEZONE           223      1                 CST  223              NaN           NaN        NaN         NaN         NaN         NaN         NaN
END_DATE_TIME         223    200  12-FEB-50 12:00:00    3              NaN           NaN        NaN         NaN         NaN         NaN         NaN
INJURIES_DIRECT     223.0    NaN                 NaN  NaN         2.955157      9.273995        0.0         0.0         0.0         2.0       101.0
INJURIES_INDIRECT   223.0    NaN                 NaN  NaN              0.0           0.0        0.0         0.0         0.0         0.0         0.0
DEATHS_DIRECT       223.0    NaN                 NaN  NaN         0.313901      1.277009        0.0         0.0         0.0         0.0         9.0
DEATHS_INDIRECT     223.0    NaN                 NaN  NaN              0.0           0.0        0.0         0.0         0.0         0.0         0.0
DAMAGE_PROPERTY       223      7                 25K   75              NaN           NaN        NaN         NaN         NaN         NaN         NaN
DAMAGE_CROPS        223.0    NaN                 NaN  NaN              0.0           0.0        0.0         0.0         0.0         0.0         0.0
SOURCE                0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
MAGNITUDE           223.0    NaN                 NaN  NaN              0.0           0.0        0.0         0.0         0.0         0.0         0.0
MAGNITUDE_TYPE        0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
FLOOD_CAUSE           0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
CATEGORY              0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
TOR_F_SCALE           217      5                  F1   84              NaN           NaN        NaN         NaN         NaN         NaN         NaN
TOR_LENGTH          223.0    NaN                 NaN  NaN         5.761883      7.955945        0.0        0.25         2.0        8.55        50.3
TOR_WIDTH           223.0    NaN                 NaN  NaN       138.825112    209.443538        7.0        33.0        50.0       150.0      1760.0
TOR_OTHER_WFO         0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
TOR_OTHER_CZ_STATE    0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
TOR_OTHER_CZ_FIPS     0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
TOR_OTHER_CZ_NAME     0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
BEGIN_RANGE           0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
BEGIN_AZIMUTH         0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
BEGIN_LOCATION        0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
END_RANGE             0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
END_AZIMUTH           0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
END_LOCATION          0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
BEGIN_LAT           223.0    NaN                 NaN  NaN        36.243857      4.157164      26.88      32.615       35.75      39.365       48.92
BEGIN_LON           223.0    NaN                 NaN  NaN       -92.584978      6.902682    -110.42     -97.625       -93.3      -89.59      -72.57
END_LAT             115.0    NaN                 NaN  NaN         36.27713      4.291072      26.88        32.6       35.33       39.34       48.78
END_LON             115.0    NaN                 NaN  NaN       -93.855043      5.574331     -107.3      -97.95       -93.7     -90.145      -75.47
EPISODE_NARRATIVE     0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
EVENT_NARRATIVE       0.0    NaN                 NaN  NaN              NaN           NaN        NaN         NaN         NaN         NaN         NaN
DATA_SOURCE           223      1                 PUB  223              NaN           NaN        NaN         NaN         NaN         NaN         NaN

In [7]:
sparsity_report(storm, 'Storm events details')

--- Storm events details: sparsity ---
                    null_count  null_pct    dtype
BEGIN_AZIMUTH              223    100.00  float64
BEGIN_LOCATION             223    100.00  float64
MAGNITUDE_TYPE             223    100.00  float64
FLOOD_CAUSE                223    100.00  float64
CATEGORY                   223    100.00  float64
TOR_OTHER_WFO              223    100.00  float64
TOR_OTHER_CZ_STATE         223    100.00  float64
TOR_OTHER_CZ_FIPS          223    100.00  float64
WFO                        223    100.00  float64
TOR_OTHER_CZ_NAME          223    100.00  float64
BEGIN_RANGE                223    100.00  float64
SOURCE                     223    100.00  float64
END_RANGE                  223    100.00  float64
END_AZIMUTH                223    100.00  float64
END_LOCATION               223    100.00  float64
EPISODE_ID                 223    100.00  float64
EPISODE_NARRATIVE          223    100.00  float64
EVENT_NARRATIVE            223    100.00  float64
END_LAT                    108     48.43  float64
END_LON                    108     48.43  float64
TOR_F_SCALE                  6      2.69      str
MAGNITUDE                    0      0.00    int64
BEGIN_LAT                    0      0.00  float64
BEGIN_LON                    0      0.00  float64
TOR_WIDTH                    0      0.00    int64
TOR_LENGTH                   0      0.00  float64
BEGIN_YEARMONTH              0      0.00    int64
DAMAGE_CROPS                 0      0.00    int64
BEGIN_DAY                    0      0.00    int64
EVENT_TYPE                   0      0.00      str
BEGIN_TIME                   0      0.00    int64
END_YEARMONTH                0      0.00    int64
END_DAY                      0      0.00    int64
END_TIME                     0      0.00    int64
EVENT_ID                     0      0.00    int64
STATE                        0      0.00      str
STATE_FIPS                   0      0.00    int64
YEAR                         0      0.00    int64
MONTH_NAME                   0      0.00      str
CZ_TYPE                      0      0.00      str
DAMAGE_PROPERTY              0      0.00      str
CZ_FIPS                      0      0.00    int64
CZ_NAME                      0      0.00      str
BEGIN_DATE_TIME              0      0.00      str
CZ_TIMEZONE                  0      0.00      str
END_DATE_TIME                0      0.00      str
INJURIES_DIRECT              0      0.00    int64
INJURIES_INDIRECT            0      0.00    int64
DEATHS_DIRECT                0      0.00    int64
DEATHS_INDIRECT              0      0.00    int64
DATA_SOURCE                  0      0.00      str

                    null_count  null_pct    dtype
BEGIN_AZIMUTH              223    100.00  float64
BEGIN_LOCATION             223    100.00  float64
MAGNITUDE_TYPE             223    100.00  float64
FLOOD_CAUSE                223    100.00  float64
CATEGORY                   223    100.00  float64
TOR_OTHER_WFO              223    100.00  float64
TOR_OTHER_CZ_STATE         223    100.00  float64
TOR_OTHER_CZ_FIPS          223    100.00  float64
WFO                        223    100.00  float64
TOR_OTHER_CZ_NAME          223    100.00  float64
BEGIN_RANGE                223    100.00  float64
SOURCE                     223    100.00  float64
END_RANGE                  223    100.00  float64
END_AZIMUTH                223    100.00  float64
END_LOCATION               223    100.00  float64
EPISODE_ID                 223    100.00  float64
EPISODE_NARRATIVE          223    100.00  float64
EVENT_NARRATIVE            223    100.00  float64
END_LAT                    108     48.43  float64
END_LON                    108     48.43  float64
TOR_F_SCALE                  6      2.69      str
MAGNITUDE                    0      0.00    int64
BEGIN_LAT                    0      0.00  float64
BEGIN_LON                    0      0.00  float64
TOR_WIDTH                    0      0.00    int64
TOR_LENGTH                   0      0.00  float64
BEGIN_YEARMONTH              0      0.00    int64
DAMAGE_CROPS                 0      0.00    int64
BEGIN_DAY                    0      0.00    int64
EVENT_TYPE                   0      0.00      str
BEGIN_TIME                   0      0.00    int64
END_YEARMONTH                0      0.00    int64
END_DAY                      0      0.00    int64
END_TIME                     0      0.00    int64
EVENT_ID                     0      0.00    int64
STATE                        0      0.00      str
STATE_FIPS                   0      0.00    int64
YEAR                         0      0.00    int64
MONTH_NAME                   0      0.00      str
CZ_TYPE                      0      0.00      str
DAMAGE_PROPERTY              0      0.00      str
CZ_FIPS                      0      0.00    int64
CZ_NAME                      0      0.00      str
BEGIN_DATE_TIME              0      0.00      str
CZ_TIMEZONE                  0      0.00      str
END_DATE_TIME                0      0.00      str
INJURIES_DIRECT              0      0.00    int64
INJURIES_INDIRECT            0      0.00    int64
DEATHS_DIRECT                0      0.00    int64
DEATHS_INDIRECT              0      0.00    int64
DATA_SOURCE                  0      0.00      str

In [8]:
plants_path = 'power-plants/august_generator2026.xlsx'
plant_sheets = ['Operating', 'Planned', 'Retired', 'Canceled or Postponed', 'Operating_PR', 'Planned_PR', 'Retired_PR']
plants = {name: pd.read_excel(plants_path, sheet_name=name, header=2) for name in plant_sheets}
for name, df in plants.items():
    print(name, df.shape)

Operating (28379, 37)
Planned (2313, 23)
Retired (7338, 26)
Canceled or Postponed (1743, 20)
Operating_PR (230, 37)
Planned_PR (7, 23)
Retired_PR (12, 26)

In [9]:
plants['Operating'].dtypes

Entity ID                                  object
Entity Name                                   str
Plant ID                                  float64
Plant Name                                    str
Google Map                                    str
Bing Map                                      str
Plant State                                   str
County                                        str
Balancing Authority Code                      str
Sector                                        str
Generator ID                                  str
Unit Code                                     str
Nameplate Capacity (MW)                   float64
Net Summer Capacity (MW)                   object
Net Winter Capacity (MW)                   object
Technology                                    str
Energy Source Code                            str
Prime Mover Code                              str
Operating Month                           float64
Operating Year                            float64
Planned Retirement Month                   object
Planned Retirement Year                    object
Status                                        str
Nameplate Energy Capacity (MWh)            object
DC Net Capacity (MW)                       object
Planned Derate Year                        object
Planned Derate Month                       object
Planned Derate of Summer Capacity (MW)     object
Planned Uprate Year                        object
Planned Uprate Month                       object
Planned Uprate of Summer Capacity (MW)     object
Planned Repower Year                       object
Planned Repower Month                      object
Other Modification Year                    object
Other Modification Month                   object
Latitude                                  float64
Longitude                                 float64
dtype: object

In [10]:
plants['Operating'].describe(include='all').T

                                          count  unique                                      top    freq          mean           std       min       25%      50%        75%      max
Entity ID                               28378.0  6027.0                                  55938.0   329.0           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Entity Name                               28377    6016  Industrial Power Generating Company LLC     329           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Plant ID                                28377.0     NaN                                      NaN     NaN  42795.831096  26771.909134       1.0    7266.0  56954.0    62967.0  70438.0
Plant Name                                28377   14698                             Edison Sault      73           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Google Map                                28377       1                                      Map   28377           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Bing Map                                  28377       1                                      Map   28377           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Plant State                               28377      51                                       CA    3228           NaN           NaN       NaN       NaN      NaN        NaN      NaN
County                                    28377    1486                              Los Angeles     439           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Balancing Authority Code                  27642      65                                     MISO    5023           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Sector                                    28377       7                              IPP Non-CHP   14526           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Generator ID                              28376   11253                                        1    2941           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Unit Code                                  2196     318                                      CC1     770           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Nameplate Capacity (MW)                 28377.0     NaN                                      NaN     NaN     49.740008    119.081512       0.1       1.5      4.5       48.0   2561.2
Net Summer Capacity (MW)                28377.0  2129.0                                      2.0  1584.0           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Net Winter Capacity (MW)                28377.0  2110.0                                      2.0  1557.0           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Technology                                28376      27                       Solar Photovoltaic    8281           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Energy Source Code                        28376      35                                      SUN    8293           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Prime Mover Code                          28377      18                                       PV    8281           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Operating Month                         28377.0     NaN                                      NaN     NaN       6.86919      3.626196       1.0       4.0      7.0       10.0     12.0
Operating Year                          28377.0     NaN                                      NaN     NaN   1999.505057      27.53718    1891.0    1989.0   2010.0     2019.0   2026.0
Planned Retirement Month                  28377      13                                            27853           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Retirement Year                   28377      37                                            27846           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Status                                    28377       4                           (OP) Operating   26126           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Nameplate Energy Capacity (MWh)           28377     315                                            27243           NaN           NaN       NaN       NaN      NaN        NaN      NaN
DC Net Capacity (MW)                      28377    1316                                            20364           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Derate Year                       28377       2                                            28376           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Derate Month                      28377       2                                            28376           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Derate of Summer Capacity (MW)    28377       3                                            28364           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Uprate Year                       28376      11                                            28227           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Uprate Month                      28376      13                                            28227           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Uprate of Summer Capacity (MW)    28376      54                                            28224           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Repower Year                      28369       7                                            28314           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Planned Repower Month                     28369      11                                            28314           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Other Modification Year                   28367      13                                            28284           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Other Modification Month                  28367      13                                            28284           NaN           NaN       NaN       NaN      NaN        NaN      NaN
Latitude                                28377.0     NaN                                      NaN     NaN     38.875787      6.085965   18.9742    34.831  39.5871  42.506156   71.292
Longitude                               28377.0     NaN                                      NaN     NaN    -93.933216       18.5076 -171.7124 -104.5492 -90.4167    -78.913 -67.4012

In [11]:
sparsity_report(plants['Operating'], 'Power plants - Operating')

--- Power plants - Operating: sparsity ---
                                        null_count  null_pct    dtype
Unit Code                                    26183     92.26      str
Balancing Authority Code                       737      2.60      str
Other Modification Month                        12      0.04   object
Other Modification Year                         12      0.04   object
Planned Repower Month                           10      0.04   object
Planned Repower Year                            10      0.04   object
Operating Month                                  2      0.01  float64
Planned Derate Month                             2      0.01   object
Status                                           2      0.01      str
Nameplate Energy Capacity (MWh)                  2      0.01   object
DC Net Capacity (MW)                             2      0.01   object
Planned Derate Year                              2      0.01   object
Planned Uprate Month                             3      0.01   object
Planned Derate of Summer Capacity (MW)           2      0.01   object
Planned Uprate Year                              3      0.01   object
Planned Retirement Month                         2      0.01   object
Planned Uprate of Summer Capacity (MW)           3      0.01   object
Latitude                                         2      0.01  float64
Planned Retirement Year                          2      0.01   object
Longitude                                        2      0.01  float64
Operating Year                                   2      0.01  float64
Sector                                           2      0.01      str
Plant ID                                         2      0.01  float64
Plant Name                                       2      0.01      str
Google Map                                       2      0.01      str
Bing Map                                         2      0.01      str
Plant State                                      2      0.01      str
County                                           2      0.01      str
Generator ID                                     3      0.01      str
Entity Name                                      2      0.01      str
Nameplate Capacity (MW)                          2      0.01  float64
Net Summer Capacity (MW)                         2      0.01   object
Net Winter Capacity (MW)                         2      0.01   object
Technology                                       3      0.01      str
Energy Source Code                               3      0.01      str
Prime Mover Code                                 2      0.01      str
Entity ID                                        1      0.00   object

                                        null_count  null_pct    dtype
Unit Code                                    26183     92.26      str
Balancing Authority Code                       737      2.60      str
Other Modification Month                        12      0.04   object
Other Modification Year                         12      0.04   object
Planned Repower Month                           10      0.04   object
Planned Repower Year                            10      0.04   object
Operating Month                                  2      0.01  float64
Planned Derate Month                             2      0.01   object
Status                                           2      0.01      str
Nameplate Energy Capacity (MWh)                  2      0.01   object
DC Net Capacity (MW)                             2      0.01   object
Planned Derate Year                              2      0.01   object
Planned Uprate Month                             3      0.01   object
Planned Derate of Summer Capacity (MW)           2      0.01   object
Planned Uprate Year                              3      0.01   object
Planned Retirement Month                         2      0.01   object
Planned Uprate of Summer Capacity (MW)           3      0.01   object
Latitude                                         2      0.01  float64
Planned Retirement Year                          2      0.01   object
Longitude                                        2      0.01  float64
Operating Year                                   2      0.01  float64
Sector                                           2      0.01      str
Plant ID                                         2      0.01  float64
Plant Name                                       2      0.01      str
Google Map                                       2      0.01      str
Bing Map                                         2      0.01      str
Plant State                                      2      0.01      str
County                                           2      0.01      str
Generator ID                                     3      0.01      str
Entity Name                                      2      0.01      str
Nameplate Capacity (MW)                          2      0.01  float64
Net Summer Capacity (MW)                         2      0.01   object
Net Winter Capacity (MW)                         2      0.01   object
Technology                                       3      0.01      str
Energy Source Code                               3      0.01      str
Prime Mover Code                                 2      0.01      str
Entity ID                                        1      0.00   object

In [12]:
plants['Planned'].dtypes

Entity ID                    object
Entity Name                     str
Plant ID                    float64
Plant Name                      str
Google Map                      str
Bing Map                        str
Plant State                     str
County                          str
Balancing Authority Code        str
Sector                          str
Generator ID                    str
Unit Code                       str
Nameplate Capacity (MW)     float64
Net Summer Capacity (MW)    float64
Net Winter Capacity (MW)    float64
Technology                      str
Energy Source Code              str
Prime Mover Code                str
Planned Operation Month     float64
Planned Operation Year      float64
Status                          str
Latitude                    float64
Longitude                   float64
dtype: object

In [13]:
plants['Planned'].describe(include='all').T

                           count unique                                                top   freq          mean           std        min        25%        50%        75%      max
Entity ID                 2312.0  975.0                                            67738.0  157.0           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Entity Name                 2311    974                                      Fermi America    157           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Plant ID                  2311.0    NaN                                                NaN    NaN  64495.364777  14476.004911       56.0    66555.0    68569.0    69799.0  70452.0
Plant Name                  2311   1580                    Project Matador Gas Plant (PMG)    157           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Google Map                  2311      1                                                Map   2311           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Bing Map                    2311      1                                                Map   2311           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Plant State                 2311     51                                                 TX    545           NaN           NaN        NaN        NaN        NaN        NaN      NaN
County                      2310    627                                             Carson    161           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Balancing Authority Code    2304     47                                               ERCO    522           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Sector                      2311      7                                        IPP Non-CHP   1865           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Generator ID                2310   1970                                                  1     47           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Unit Code                    219     65                                                  1      9           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Nameplate Capacity (MW)   2311.0    NaN                                                NaN    NaN    124.856729    170.093212        0.1        5.0       60.5      200.0   2640.0
Net Summer Capacity (MW)  2311.0    NaN                                                NaN    NaN    121.579662    166.183488        0.1        5.0       57.0      200.0   2640.0
Net Winter Capacity (MW)  2311.0    NaN                                                NaN    NaN    122.598918    167.615864        0.1        5.0       60.0      200.0   2640.0
Technology                  2311     18                                 Solar Photovoltaic   1075           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Energy Source Code          2311     17                                                SUN   1076           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Prime Mover Code            2311     15                                                 PV   1075           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Planned Operation Month   2311.0    NaN                                                NaN    NaN      8.774556       3.37559        1.0        6.0       10.0       12.0     12.0
Planned Operation Year    2311.0    NaN                                                NaN    NaN   2027.487668      1.397493     2026.0     2026.0     2027.0     2028.0   2039.0
Status                      2311      6  (P) Planned for installation, but regulatory a...    682           NaN           NaN        NaN        NaN        NaN        NaN      NaN
Latitude                  2311.0    NaN                                                NaN    NaN     36.881176       4.85114  19.843504  33.581065  36.682944  40.708897  57.9449
Longitude                 2311.0    NaN                                                NaN    NaN    -95.671374     15.356505    -159.45  -103.2641  -95.45472 -83.831485   -68.11

In [14]:
sparsity_report(plants['Planned'], 'Power plants - Planned')

--- Power plants - Planned: sparsity ---
                          null_count  null_pct    dtype
Unit Code                       2094     90.53      str
Balancing Authority Code           9      0.39      str
County                             3      0.13      str
Generator ID                       3      0.13      str
Net Summer Capacity (MW)           2      0.09  float64
Latitude                           2      0.09  float64
Status                             2      0.09      str
Planned Operation Year             2      0.09  float64
Planned Operation Month            2      0.09  float64
Prime Mover Code                   2      0.09      str
Energy Source Code                 2      0.09      str
Technology                         2      0.09      str
Net Winter Capacity (MW)           2      0.09  float64
Longitude                          2      0.09  float64
Nameplate Capacity (MW)            2      0.09  float64
Entity Name                        2      0.09      str
Sector                             2      0.09      str
Plant State                        2      0.09      str
Bing Map                           2      0.09      str
Google Map                         2      0.09      str
Plant Name                         2      0.09      str
Plant ID                           2      0.09  float64
Entity ID                          1      0.04   object

                          null_count  null_pct    dtype
Unit Code                       2094     90.53      str
Balancing Authority Code           9      0.39      str
County                             3      0.13      str
Generator ID                       3      0.13      str
Net Summer Capacity (MW)           2      0.09  float64
Latitude                           2      0.09  float64
Status                             2      0.09      str
Planned Operation Year             2      0.09  float64
Planned Operation Month            2      0.09  float64
Prime Mover Code                   2      0.09      str
Energy Source Code                 2      0.09      str
Technology                         2      0.09      str
Net Winter Capacity (MW)           2      0.09  float64
Longitude                          2      0.09  float64
Nameplate Capacity (MW)            2      0.09  float64
Entity Name                        2      0.09      str
Sector                             2      0.09      str
Plant State                        2      0.09      str
Bing Map                           2      0.09      str
Google Map                         2      0.09      str
Plant Name                         2      0.09      str
Plant ID                           2      0.09  float64
Entity ID                          1      0.04   object

In [15]:
plants['Retired'].dtypes

Entity ID                           object
Entity Name                            str
Plant ID                            object
Plant Name                             str
Google Map                             str
Bing Map                               str
Plant State                            str
County                                 str
Balancing Authority Code               str
Sector                                 str
Generator ID                           str
Unit Code                              str
Nameplate Capacity (MW)            float64
Net Summer Capacity (MW)            object
Net Winter Capacity (MW)            object
Technology                             str
Energy Source Code                     str
Prime Mover Code                       str
Operating Month                     object
Operating Year                      object
Retirement Month                   float64
Retirement Year                    float64
Nameplate Energy Capacity (MWh)     object
DC Net Capacity (MW)                object
Latitude                            object
Longitude                           object
dtype: object

In [16]:
plants['Retired'].describe(include='all').T

                                  count  unique                            top    freq         mean         std     min     25%     50%     75%     max
Entity ID                        7337.0  1726.0                        17609.0   142.0          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Entity Name                        7336    1728  Southern California Edison Co     142          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Plant ID                         7336.0  2659.0                        56693.0    36.0          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Plant Name                         7336    2661                 Virginia Beach      36          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Google Map                         7280       1                            Map    7280          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Bing Map                           7280       1                            Map    7280          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Plant State                        7336      52                             CA     861          NaN         NaN     NaN     NaN     NaN     NaN     NaN
County                             7336     927                 San Bernardino     162          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Balancing Authority Code           5910      58                           MISO    1339          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Sector                             7322       7               Electric Utility    3284          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Generator ID                       7336    1737                              1     849          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Unit Code                           193      40                            CC1      99          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Nameplate Capacity (MW)          7336.0     NaN                            NaN     NaN    42.007375  114.307725     0.1     1.0     3.0    25.0  1425.6
Net Summer Capacity (MW)         7336.0   805.0                            0.5   339.0          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Net Winter Capacity (MW)         7336.0   809.0                            0.5   344.0          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Technology                         7336      23              Petroleum Liquids    1989          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Energy Source Code                 7336      34                             NG    2309          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Prime Mover Code                   7336      15                             IC    2855          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Operating Month                  7336.0    16.0                            1.0  1154.0          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Operating Year                   7336.0   125.0                         2001.0   212.0          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Retirement Month                 7336.0     NaN                            NaN     NaN     7.196701    3.811101     1.0     4.0     7.0    11.0    12.0
Retirement Year                  7336.0     NaN                            NaN     NaN  2014.090785    7.006663  1963.0  2009.0  2014.0  2020.0  2026.0
Nameplate Energy Capacity (MWh)    7336      28                                   7290          NaN         NaN     NaN     NaN     NaN     NaN     NaN
DC Net Capacity (MW)               7336      22                                   7170          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Latitude                           7336    2601                                     50          NaN         NaN     NaN     NaN     NaN     NaN     NaN
Longitude                          7336    2596                                     53          NaN         NaN     NaN     NaN     NaN     NaN     NaN

In [17]:
sparsity_report(plants['Retired'], 'Power plants - Retired')

--- Power plants - Retired: sparsity ---
                                 null_count  null_pct    dtype
Unit Code                              7145     97.37      str
Balancing Authority Code               1428     19.46      str
Google Map                               58      0.79      str
Bing Map                                 58      0.79      str
Sector                                   16      0.22      str
Net Summer Capacity (MW)                  2      0.03   object
Energy Source Code                        2      0.03      str
Latitude                                  2      0.03   object
DC Net Capacity (MW)                      2      0.03   object
Nameplate Energy Capacity (MWh)           2      0.03   object
Retirement Year                           2      0.03  float64
Retirement Month                          2      0.03  float64
Operating Year                            2      0.03   object
Operating Month                           2      0.03   object
Prime Mover Code                          2      0.03      str
Longitude                                 2      0.03   object
Technology                                2      0.03      str
Net Winter Capacity (MW)                  2      0.03   object
Entity Name                               2      0.03      str
Nameplate Capacity (MW)                   2      0.03  float64
Generator ID                              2      0.03      str
County                                    2      0.03      str
Plant State                               2      0.03      str
Plant Name                                2      0.03      str
Plant ID                                  2      0.03   object
Entity ID                                 1      0.01   object

                                 null_count  null_pct    dtype
Unit Code                              7145     97.37      str
Balancing Authority Code               1428     19.46      str
Google Map                               58      0.79      str
Bing Map                                 58      0.79      str
Sector                                   16      0.22      str
Net Summer Capacity (MW)                  2      0.03   object
Energy Source Code                        2      0.03      str
Latitude                                  2      0.03   object
DC Net Capacity (MW)                      2      0.03   object
Nameplate Energy Capacity (MWh)           2      0.03   object
Retirement Year                           2      0.03  float64
Retirement Month                          2      0.03  float64
Operating Year                            2      0.03   object
Operating Month                           2      0.03   object
Prime Mover Code                          2      0.03      str
Longitude                                 2      0.03   object
Technology                                2      0.03      str
Net Winter Capacity (MW)                  2      0.03   object
Entity Name                               2      0.03      str
Nameplate Capacity (MW)                   2      0.03  float64
Generator ID                              2      0.03      str
County                                    2      0.03      str
Plant State                               2      0.03      str
Plant Name                                2      0.03      str
Plant ID                                  2      0.03   object
Entity ID                                 1      0.01   object

In [18]:
plants['Canceled or Postponed'].dtypes

Entity ID                    object
Entity Name                     str
Plant ID                    float64
Plant Name                      str
Google Map                      str
Bing Map                        str
Plant State                     str
County                          str
Balancing Authority Code        str
Sector                          str
Generator ID                    str
Unit Code                       str
Nameplate Capacity (MW)     float64
Net Summer Capacity (MW)     object
Net Winter Capacity (MW)     object
Technology                      str
Energy Source Code              str
Prime Mover Code                str
Latitude                     object
Longitude                    object
dtype: object

In [19]:
plants['Canceled or Postponed'].describe(include='all').T

                           count unique                             top   freq          mean           std   min      25%      50%      75%      max
Entity ID                 1742.0  729.0                         17609.0  136.0           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Entity Name                 1741    727   Southern California Edison Co    136           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Plant ID                  1741.0    NaN                             NaN    NaN  53334.530729  18800.299421  54.0  56653.0  59006.0  62400.0  69162.0
Plant Name                  1741   1068  Solar Photovoltaic Project #40     20           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Google Map                  1672      1                             Map   1672           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Bing Map                    1672      1                             Map   1672           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Plant State                 1741     51                              CA    285           NaN           NaN   NaN      NaN      NaN      NaN      NaN
County                      1706    490                  San Bernardino    106           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Balancing Authority Code    1607     44                             PJM    320           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Sector                      1741      7                     IPP Non-CHP   1195           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Generator ID                1740   1005                               1    136           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Unit Code                     80     15                             S40     20           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Nameplate Capacity (MW)   1741.0    NaN                             NaN    NaN    106.298621     175.06854   0.0      3.4     35.5    170.0   2250.0
Net Summer Capacity (MW)  1741.0  415.0                             0.5  150.0           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Net Winter Capacity (MW)  1741.0  399.0                             0.5  150.0           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Technology                  1741     27              Solar Photovoltaic    634           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Energy Source Code          1741     24                             SUN    643           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Prime Mover Code            1741     19                              PV    634           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Latitude                    1741   1027                                     69           NaN           NaN   NaN      NaN      NaN      NaN      NaN
Longitude                   1741   1021                                     69           NaN           NaN   NaN      NaN      NaN      NaN      NaN

In [20]:
sparsity_report(plants['Canceled or Postponed'], 'Power plants - Canceled or Postponed')

--- Power plants - Canceled or Postponed: sparsity ---
                          null_count  null_pct    dtype
Unit Code                       1663     95.41      str
Balancing Authority Code         136      7.80      str
Google Map                        71      4.07      str
Bing Map                          71      4.07      str
County                            37      2.12      str
Generator ID                       3      0.17      str
Net Summer Capacity (MW)           2      0.11   object
Latitude                           2      0.11   object
Prime Mover Code                   2      0.11      str
Energy Source Code                 2      0.11      str
Technology                         2      0.11      str
Net Winter Capacity (MW)           2      0.11   object
Longitude                          2      0.11   object
Nameplate Capacity (MW)            2      0.11  float64
Entity Name                        2      0.11      str
Sector                             2      0.11      str
Plant State                        2      0.11      str
Plant Name                         2      0.11      str
Plant ID                           2      0.11  float64
Entity ID                          1      0.06   object

                          null_count  null_pct    dtype
Unit Code                       1663     95.41      str
Balancing Authority Code         136      7.80      str
Google Map                        71      4.07      str
Bing Map                          71      4.07      str
County                            37      2.12      str
Generator ID                       3      0.17      str
Net Summer Capacity (MW)           2      0.11   object
Latitude                           2      0.11   object
Prime Mover Code                   2      0.11      str
Energy Source Code                 2      0.11      str
Technology                         2      0.11      str
Net Winter Capacity (MW)           2      0.11   object
Longitude                          2      0.11   object
Nameplate Capacity (MW)            2      0.11  float64
Entity Name                        2      0.11      str
Sector                             2      0.11      str
Plant State                        2      0.11      str
Plant Name                         2      0.11      str
Plant ID                           2      0.11  float64
Entity ID                          1      0.06   object

In [21]:
plants['Operating_PR'].dtypes

Entity ID                                  object
Entity Name                                   str
Plant ID                                  float64
Plant Name                                    str
Google Map                                    str
Bing Map                                      str
Plant State                                   str
County                                        str
Balancing Authority Code                  float64
Sector                                        str
Generator ID                                  str
Unit Code                                     str
Nameplate Capacity (MW)                   float64
Net Summer Capacity (MW)                   object
Net Winter Capacity (MW)                   object
Technology                                    str
Energy Source Code                            str
Prime Mover Code                              str
Operating Month                           float64
Operating Year                            float64
Planned Retirement Month                   object
Planned Retirement Year                    object
Status                                        str
Nameplate Energy Capacity (MWh)            object
DC Net Capacity (MW)                       object
Planned Derate Year                           str
Planned Derate Month                          str
Planned Derate of Summer Capacity (MW)        str
Planned Uprate Year                           str
Planned Uprate Month                          str
Planned Uprate of Summer Capacity (MW)        str
Planned Repower Year                       object
Planned Repower Month                      object
Other Modification Year                    object
Other Modification Month                   object
Latitude                                  float64
Longitude                                 float64
dtype: object

In [22]:
plants['Operating_PR'].describe(include='all').T

                                        count unique                                 top  freq          mean          std        min       25%        50%      75%        max
Entity ID                               229.0   44.0                             15497.0  79.0           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Entity Name                               228     43  Puerto Rico Electric Pwr Authority    79           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Plant ID                                228.0    NaN                                 NaN   NaN  63036.890351  2385.346987    61014.0   61148.0    61639.0  66057.0    68916.0
Plant Name                                228     67                       Aguirre Plant    14           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Google Map                                228      1                                 Map   228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Bing Map                                  228      1                                 Map   228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Plant State                               228      1                                  PR   228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
County                                    150     28                             Arecibo    17           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Balancing Authority Code                  0.0    NaN                                 NaN   NaN           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Sector                                    228      7                    Electric Utility    85           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Generator ID                              228    162                                   1    14           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Unit Code                                  20      8                                 CC1     5           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Nameplate Capacity (MW)                 228.0    NaN                                 NaN   NaN     28.396053    70.124005        0.1       1.3        2.0     21.0      450.0
Net Summer Capacity (MW)                228.0   69.0                                 2.0  21.0           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Net Winter Capacity (MW)                228.0   69.0                                 2.0  21.0           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Technology                                228     10                   Petroleum Liquids   146           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Energy Source Code                        228     10                                 DFO   123           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Prime Mover Code                          228      9                                  IC   117           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Operating Month                         228.0    NaN                                 NaN   NaN      6.421053     3.781231        1.0       3.0        7.0     10.0       12.0
Operating Year                          228.0    NaN                                 NaN   NaN   1997.942982    24.213465     1929.0    1977.0     2007.0   2018.0     2026.0
Planned Retirement Month                  228      2                                       227           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Retirement Year                   228      2                                       227           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Status                                    228      4                      (OP) Operating   143           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Nameplate Energy Capacity (MWh)           228      7                                       219           NaN          NaN        NaN       NaN        NaN      NaN        NaN
DC Net Capacity (MW)                      228     19                                       208           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Derate Year                       228      1                                       228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Derate Month                      228      1                                       228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Derate of Summer Capacity (MW)    228      1                                       228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Uprate Year                       228      1                                       228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Uprate Month                      228      1                                       228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Uprate of Summer Capacity (MW)    228      1                                       228           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Repower Year                      228      2                                       226           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Planned Repower Month                     228      2                                       226           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Other Modification Year                   228      2                                       227           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Other Modification Month                  228      2                                       227           NaN          NaN        NaN       NaN        NaN      NaN        NaN
Latitude                                228.0    NaN                                 NaN   NaN     18.268264     0.174897  17.947115  18.13778  18.316713  18.4271  18.498007
Longitude                               228.0    NaN                                 NaN   NaN    -66.276729     0.427533   -67.1592  -66.5998  -66.15043 -65.9631  -65.27956

In [23]:
sparsity_report(plants['Operating_PR'], 'Power plants - Operating_PR')

--- Power plants - Operating_PR: sparsity ---
                                        null_count  null_pct    dtype
Balancing Authority Code                       230    100.00  float64
Unit Code                                      210     91.30      str
County                                          80     34.78      str
Operating Month                                  2      0.87  float64
Status                                           2      0.87      str
Nameplate Energy Capacity (MWh)                  2      0.87   object
DC Net Capacity (MW)                             2      0.87   object
Planned Derate Year                              2      0.87      str
Planned Derate Month                             2      0.87      str
Planned Derate of Summer Capacity (MW)           2      0.87      str
Planned Uprate Year                              2      0.87      str
Planned Uprate Month                             2      0.87      str
Planned Retirement Month                         2      0.87   object
Planned Uprate of Summer Capacity (MW)           2      0.87      str
Planned Repower Year                             2      0.87   object
Planned Repower Month                            2      0.87   object
Other Modification Year                          2      0.87   object
Other Modification Month                         2      0.87   object
Latitude                                         2      0.87  float64
Planned Retirement Year                          2      0.87   object
Longitude                                        2      0.87  float64
Operating Year                                   2      0.87  float64
Entity Name                                      2      0.87      str
Prime Mover Code                                 2      0.87      str
Energy Source Code                               2      0.87      str
Technology                                       2      0.87      str
Net Winter Capacity (MW)                         2      0.87   object
Net Summer Capacity (MW)                         2      0.87   object
Nameplate Capacity (MW)                          2      0.87  float64
Generator ID                                     2      0.87      str
Sector                                           2      0.87      str
Plant State                                      2      0.87      str
Bing Map                                         2      0.87      str
Google Map                                       2      0.87      str
Plant Name                                       2      0.87      str
Plant ID                                         2      0.87  float64
Entity ID                                        1      0.43   object

                                        null_count  null_pct    dtype
Balancing Authority Code                       230    100.00  float64
Unit Code                                      210     91.30      str
County                                          80     34.78      str
Operating Month                                  2      0.87  float64
Status                                           2      0.87      str
Nameplate Energy Capacity (MWh)                  2      0.87   object
DC Net Capacity (MW)                             2      0.87   object
Planned Derate Year                              2      0.87      str
Planned Derate Month                             2      0.87      str
Planned Derate of Summer Capacity (MW)           2      0.87      str
Planned Uprate Year                              2      0.87      str
Planned Uprate Month                             2      0.87      str
Planned Retirement Month                         2      0.87   object
Planned Uprate of Summer Capacity (MW)           2      0.87      str
Planned Repower Year                             2      0.87   object
Planned Repower Month                            2      0.87   object
Other Modification Year                          2      0.87   object
Other Modification Month                         2      0.87   object
Latitude                                         2      0.87  float64
Planned Retirement Year                          2      0.87   object
Longitude                                        2      0.87  float64
Operating Year                                   2      0.87  float64
Entity Name                                      2      0.87      str
Prime Mover Code                                 2      0.87      str
Energy Source Code                               2      0.87      str
Technology                                       2      0.87      str
Net Winter Capacity (MW)                         2      0.87   object
Net Summer Capacity (MW)                         2      0.87   object
Nameplate Capacity (MW)                          2      0.87  float64
Generator ID                                     2      0.87      str
Sector                                           2      0.87      str
Plant State                                      2      0.87      str
Bing Map                                         2      0.87      str
Google Map                                       2      0.87      str
Plant Name                                       2      0.87      str
Plant ID                                         2      0.87  float64
Entity ID                                        1      0.43   object

In [24]:
plants['Planned_PR'].dtypes

Entity ID                    object
Entity Name                     str
Plant ID                    float64
Plant Name                      str
Google Map                      str
Bing Map                        str
Plant State                     str
County                          str
Balancing Authority Code    float64
Sector                          str
Generator ID                    str
Unit Code                   float64
Nameplate Capacity (MW)     float64
Net Summer Capacity (MW)    float64
Net Winter Capacity (MW)    float64
Technology                      str
Energy Source Code              str
Prime Mover Code                str
Planned Operation Month     float64
Planned Operation Year      float64
Status                          str
Latitude                    float64
Longitude                   float64
dtype: object

In [25]:
plants['Planned_PR'].describe(include='all').T

                         count unique                                                top freq       mean          std        min        25%        50%        75%        max
Entity ID                  6.0    4.0                                            65563.0  2.0        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Entity Name                  5      3                                   SRI Solar 4, LLC    2        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Plant ID                   5.0    NaN                                                NaN  NaN    65490.2  2436.602696    61133.0    66515.0    66515.0    66644.0    66644.0
Plant Name                   5      3                          PR Bayamon Ave Zaya Verde    2        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Google Map                   5      1                                                Map    5        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Bing Map                     5      1                                                Map    5        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Plant State                  5      1                                                 PR    5        NaN          NaN        NaN        NaN        NaN        NaN        NaN
County                       1      1                                            Humacao    1        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Balancing Authority Code   0.0    NaN                                                NaN  NaN        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Sector                       5      1                                        IPP Non-CHP    5        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Generator ID                 5      5                                              19639    1        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Unit Code                  0.0    NaN                                                NaN  NaN        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Nameplate Capacity (MW)    5.0    NaN                                                NaN  NaN      35.44    42.276093        0.2        2.0       20.0       55.0      100.0
Net Summer Capacity (MW)   5.0    NaN                                                NaN  NaN      35.44    42.276093        0.2        2.0       20.0       55.0      100.0
Net Winter Capacity (MW)   5.0    NaN                                                NaN  NaN      35.44    42.276093        0.2        2.0       20.0       55.0      100.0
Technology                   5      2                                 Solar Photovoltaic    3        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Energy Source Code           5      2                                                SUN    3        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Prime Mover Code             5      2                                                 PV    3        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Planned Operation Month    5.0    NaN                                                NaN  NaN        6.0     4.582576        2.0        3.0        3.0       11.0       11.0
Planned Operation Year     5.0    NaN                                                NaN  NaN     2026.6     0.547723     2026.0     2026.0     2027.0     2027.0     2027.0
Status                       5      3  (V) Under construction, more than 50 percent c...    2        NaN          NaN        NaN        NaN        NaN        NaN        NaN
Latitude                   5.0    NaN                                                NaN  NaN  18.207961     0.177952  18.053141  18.053141  18.134597  18.399464  18.399464
Longitude                  5.0    NaN                                                NaN  NaN -66.188516     0.227718  -66.37983  -66.37983  -66.18029  -66.18029  -65.82234

In [26]:
sparsity_report(plants['Planned_PR'], 'Power plants - Planned_PR')

--- Power plants - Planned_PR: sparsity ---
                          null_count  null_pct    dtype
Unit Code                          7    100.00  float64
Balancing Authority Code           7    100.00  float64
County                             6     85.71      str
Net Summer Capacity (MW)           2     28.57  float64
Latitude                           2     28.57  float64
Status                             2     28.57      str
Planned Operation Year             2     28.57  float64
Planned Operation Month            2     28.57  float64
Prime Mover Code                   2     28.57      str
Energy Source Code                 2     28.57      str
Technology                         2     28.57      str
Net Winter Capacity (MW)           2     28.57  float64
Longitude                          2     28.57  float64
Nameplate Capacity (MW)            2     28.57  float64
Entity Name                        2     28.57      str
Generator ID                       2     28.57      str
Sector                             2     28.57      str
Plant State                        2     28.57      str
Bing Map                           2     28.57      str
Google Map                         2     28.57      str
Plant Name                         2     28.57      str
Plant ID                           2     28.57  float64
Entity ID                          1     14.29   object

                          null_count  null_pct    dtype
Unit Code                          7    100.00  float64
Balancing Authority Code           7    100.00  float64
County                             6     85.71      str
Net Summer Capacity (MW)           2     28.57  float64
Latitude                           2     28.57  float64
Status                             2     28.57      str
Planned Operation Year             2     28.57  float64
Planned Operation Month            2     28.57  float64
Prime Mover Code                   2     28.57      str
Energy Source Code                 2     28.57      str
Technology                         2     28.57      str
Net Winter Capacity (MW)           2     28.57  float64
Longitude                          2     28.57  float64
Nameplate Capacity (MW)            2     28.57  float64
Entity Name                        2     28.57      str
Generator ID                       2     28.57      str
Sector                             2     28.57      str
Plant State                        2     28.57      str
Bing Map                           2     28.57      str
Google Map                         2     28.57      str
Plant Name                         2     28.57      str
Plant ID                           2     28.57  float64
Entity ID                          1     14.29   object

In [27]:
plants['Retired_PR'].dtypes

Entity ID                           object
Entity Name                            str
Plant ID                           float64
Plant Name                             str
Google Map                             str
Bing Map                               str
Plant State                            str
County                                 str
Balancing Authority Code           float64
Sector                                 str
Generator ID                           str
Unit Code                          float64
Nameplate Capacity (MW)            float64
Net Summer Capacity (MW)           float64
Net Winter Capacity (MW)           float64
Technology                             str
Energy Source Code                     str
Prime Mover Code                       str
Operating Month                    float64
Operating Year                     float64
Retirement Month                   float64
Retirement Year                    float64
Nameplate Energy Capacity (MWh)        str
DC Net Capacity (MW)                   str
Latitude                           float64
Longitude                          float64
dtype: object

In [28]:
plants['Retired_PR'].describe(include='all').T

                                count unique                   top freq       mean          std      min        25%        50%        75%        max
Entity ID                        11.0    5.0               65229.0  4.0        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Entity Name                        10      4   Bacardi Corporation    4        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Plant ID                         10.0    NaN                   NaN  NaN    63272.7  2438.369585  61132.0    61270.0    61639.0    66096.0    66096.0
Plant Name                         10      4  Bacardi Catano Plant    4        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Google Map                         10      1                   Map   10        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Bing Map                           10      1                   Map   10        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Plant State                        10      1                    PR   10        NaN          NaN      NaN        NaN        NaN        NaN        NaN
County                              8      3                Catano    4        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Balancing Authority Code          0.0    NaN                   NaN  NaN        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Sector                             10      4        Industrial CHP    4        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Generator ID                       10     10                  67P1    1        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Unit Code                         0.0    NaN                   NaN  NaN        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Nameplate Capacity (MW)          10.0    NaN                   NaN  NaN      12.99    20.744983      0.2      0.425        0.8     18.375       50.0
Net Summer Capacity (MW)         10.0    NaN                   NaN  NaN      12.98    20.747787      0.2      0.425        0.9       18.3       50.0
Net Winter Capacity (MW)         10.0    NaN                   NaN  NaN      12.99    20.741287      0.2       0.45        0.9       18.3       50.0
Technology                         10      2     Petroleum Liquids    9        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Energy Source Code                 10      3                   DFO    6        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Prime Mover Code                   10      3                    IC    6        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Operating Month                  10.0    NaN                   NaN  NaN        7.1     3.107339      2.0        7.0        7.0        9.0       12.0
Operating Year                   10.0    NaN                   NaN  NaN     1991.8     18.46799   1958.0    1995.25     1997.0    1997.75     2012.0
Retirement Month                 10.0    NaN                   NaN  NaN        7.1     3.034981      4.0        4.5        6.5        8.5       12.0
Retirement Year                  10.0    NaN                   NaN  NaN     2019.5     6.059886   2009.0     2018.0     2021.0    2024.25     2025.0
Nameplate Energy Capacity (MWh)    10      1                         10        NaN          NaN      NaN        NaN        NaN        NaN        NaN
DC Net Capacity (MW)               10      1                         10        NaN          NaN      NaN        NaN        NaN        NaN        NaN
Latitude                         10.0    NaN                   NaN  NaN  18.323981     0.186648   18.003  18.244703  18.409197  18.454087  18.454087
Longitude                        10.0    NaN                   NaN  NaN  -66.24939      0.31152 -66.7597  -66.23506 -66.189295  -66.14353   -65.6952

In [29]:
sparsity_report(plants['Retired_PR'], 'Power plants - Retired_PR')

--- Power plants - Retired_PR: sparsity ---
                                 null_count  null_pct    dtype
Balancing Authority Code                 12    100.00  float64
Unit Code                                12    100.00  float64
County                                    4     33.33      str
Net Summer Capacity (MW)                  2     16.67  float64
Technology                                2     16.67      str
Latitude                                  2     16.67  float64
DC Net Capacity (MW)                      2     16.67      str
Nameplate Energy Capacity (MWh)           2     16.67      str
Retirement Year                           2     16.67  float64
Retirement Month                          2     16.67  float64
Operating Year                            2     16.67  float64
Operating Month                           2     16.67  float64
Prime Mover Code                          2     16.67      str
Energy Source Code                        2     16.67      str
Longitude                                 2     16.67  float64
Net Winter Capacity (MW)                  2     16.67  float64
Entity Name                               2     16.67      str
Nameplate Capacity (MW)                   2     16.67  float64
Generator ID                              2     16.67      str
Sector                                    2     16.67      str
Plant State                               2     16.67      str
Bing Map                                  2     16.67      str
Google Map                                2     16.67      str
Plant Name                                2     16.67      str
Plant ID                                  2     16.67  float64
Entity ID                                 1      8.33   object

                                 null_count  null_pct    dtype
Balancing Authority Code                 12    100.00  float64
Unit Code                                12    100.00  float64
County                                    4     33.33      str
Net Summer Capacity (MW)                  2     16.67  float64
Technology                                2     16.67      str
Latitude                                  2     16.67  float64
DC Net Capacity (MW)                      2     16.67      str
Nameplate Energy Capacity (MWh)           2     16.67      str
Retirement Year                           2     16.67  float64
Retirement Month                          2     16.67  float64
Operating Year                            2     16.67  float64
Operating Month                           2     16.67  float64
Prime Mover Code                          2     16.67      str
Energy Source Code                        2     16.67      str
Longitude                                 2     16.67  float64
Net Winter Capacity (MW)                  2     16.67  float64
Entity Name                               2     16.67      str
Nameplate Capacity (MW)                   2     16.67  float64
Generator ID                              2     16.67      str
Sector                                    2     16.67      str
Plant State                               2     16.67      str
Bing Map                                  2     16.67      str
Google Map                                2     16.67      str
Plant Name                                2     16.67      str
Plant ID                                  2     16.67  float64
Entity ID                                 1      8.33   object